from building import *

cwd = GetCurrentDir()

src = Glob('./*.c')
path =  [cwd, 
         os.path.join(cwd, '../include')]

group = DefineGroup('Drivers', src, depend = ['BSP_USING_BOARD_SF32LB52_XTY_AI'], CPPPATH = path)

if GetDepend('BSP_USING_BOARD_SF32LB52_XTY_AI'):
    group = group + SConscript('../sf32lb52-xty-ai_base/script/SConscript')

Return('group')
